/**
 * @fileoverview Extracted task CRUD operations from the Pinia task store.
 *
 * Contains: removeTask, pauseTask, resumeTask, pauseAllTask, resumeAllTask,
 * toggleTask, stopSeeding, stopAllSeeding, removeTaskRecord, purgeTaskRecord,
 * batchRemoveTask.
 *
 * Uses dependency injection — accepts API + store refs instead of importing
 * them directly, enabling testability and keeping the task store thin.
 */
import { TASK_STATUS } from '@shared/constants'
import { checkTaskIsBT, checkTaskIsSeeder } from '@shared/utils'
import { logger } from '@shared/logger'
import { buildBtCompletionRecord } from '@/composables/useTaskLifecycle'
import { cleanupAria2ControlFile } from '@/composables/useFileDelete'
import { cleanupAria2MetadataFiles } from '@/composables/useDownloadCleanup'
import { useHistoryStore } from '@/stores/history'
import * as ytdlpApi from '@/api/ytdlp'
import type { Aria2Task, TaskApi } from '@shared/types'
import type { Ref } from 'vue'

/** yt-dlp direct-download tasks carry gids generated by YtdlpState in Rust
 *  (e.g. `ytdlp-1`).  They live outside aria2, so pause/remove have to take
 *  a different code path — aria2.pause/remove would fail with "invalid gid". */
function isYtdlpGid(gid: string): boolean {
  return gid.startsWith('ytdlp-')
}

interface TaskOperationsDeps {
  api: TaskApi
  taskList: Ref<Aria2Task[]>
  currentTaskGid: Ref<string>
  hideTaskDetail: () => void
  fetchList: () => Promise<void>
}

export function createTaskOperations(deps: TaskOperationsDeps) {
  const { api, taskList, currentTaskGid, hideTaskDetail, fetchList } = deps

  async function removeTask(task: Aria2Task) {
    if (task.gid === currentTaskGid.value) hideTaskDetail()

    // yt-dlp direct downloads aren't registered in aria2 — cancel the
    // sidecar process and drop the history record instead.
    if (isYtdlpGid(task.gid)) {
      try {
        await ytdlpApi.cancelDownload(task.gid)
      } catch (e) {
        logger.debug('TaskOps.removeTask.ytdlpCancel', `gid=${task.gid} ${e}`)
      }
      // Clean up yt-dlp's sidecar temp files so the Downloads folder
      // doesn't accumulate orphan `.part` / `.ytdl` blobs after a
      // partially-downloaded task is removed from the UI.
      const finalPath = task.files?.[0]?.path
      if (finalPath) {
        const { invoke } = await import('@tauri-apps/api/core')
        for (const suffix of ['.part', '.ytdl']) {
          const temp = `${finalPath}${suffix}`
          try {
            const exists = await invoke<boolean>('check_path_exists', { path: temp })
            if (exists) {
              await invoke('trash_file', { path: temp })
              logger.info('TaskOps.removeTask.trashTemp', temp)
            }
          } catch (e) {
            logger.debug('TaskOps.removeTask.trashTemp', `${temp} ${e}`)
          }
        }
      }
      try {
        await useHistoryStore().removeRecord(task.gid)
      } catch (e) {
        logger.debug('TaskOps.removeTask.ytdlpHistory', `gid=${task.gid} ${e}`)
      }
      logger.info('TaskOps.removeTask', `ytdlp gid=${task.gid}`)
      await fetchList()
      return
    }

    try {
      await api.removeTask({ gid: task.gid })
      // Purge from aria2's stopped-result list so force-save=true (BT/magnet)
      // won't persist the entry in the session file on exit.
      try {
        await api.removeTaskRecord({ gid: task.gid })
      } catch (e) {
        logger.debug('TaskOps.removeTask', `removeTaskRecord gid=${task.gid} skipped: ${e}`)
      }
      logger.info('TaskOps.removeTask', `gid=${task.gid}`)
    } finally {
      await fetchList()
      await api.saveSession()
    }
  }

  async function pauseTask(task: Aria2Task) {
    // yt-dlp direct downloads can't be paused mid-flight — the sidecar
    // process has no resume protocol. Surface a clear error so the caller
    // shows a warning instead of a generic "[object Object]".
    if (isYtdlpGid(task.gid)) {
      throw new Error('yt-dlp 任务暂不支持暂停，请使用删除中止下载')
    }

    const isBT = checkTaskIsBT(task)
    const promise = isBT ? api.forcePauseTask({ gid: task.gid }) : api.pauseTask({ gid: task.gid })
    try {
      await promise
      logger.info('TaskOps.pauseTask', `gid=${task.gid} bt=${isBT}`)
    } finally {
      await fetchList()
      await api.saveSession()
    }
  }

  async function resumeTask(task: Aria2Task) {
    if (isYtdlpGid(task.gid)) {
      throw new Error('yt-dlp 任务暂不支持恢复，请重新添加下载')
    }
    try {
      await api.resumeTask({ gid: task.gid })
      logger.info('TaskOps.resumeTask', `gid=${task.gid}`)
    } finally {
      await fetchList()
      await api.saveSession()
    }
  }

  async function pauseAllTask() {
    try {
      const nonSeeders = taskList.value.filter(
        (t) => (t.status === TASK_STATUS.ACTIVE || t.status === TASK_STATUS.WAITING) && !checkTaskIsSeeder(t),
      )
      if (nonSeeders.length > 0) {
        await Promise.allSettled(nonSeeders.map((t) => api.forcePauseTask({ gid: t.gid })))
      }
      logger.info(
        'TaskOps.pauseAllTask',
        `paused=${nonSeeders.length} gids=[${nonSeeders.map((t) => t.gid).join(',')}]`,
      )
    } finally {
      await fetchList()
      await api.saveSession()
    }
  }

  async function resumeAllTask() {
    try {
      await api.resumeAllTask()
      logger.info('TaskOps.resumeAllTask', 'resumed all paused tasks')
    } finally {
      await fetchList()
      await api.saveSession()
    }
  }

  function toggleTask(task: Aria2Task) {
    const { status } = task
    if (status === TASK_STATUS.ACTIVE && !checkTaskIsSeeder(task)) return pauseTask(task)
    if (status === TASK_STATUS.WAITING || status === TASK_STATUS.PAUSED) return resumeTask(task)
    logger.debug('TaskOps.toggleTask', `no-op gid=${task.gid} status=${status} seeder=${checkTaskIsSeeder(task)}`)
  }

  async function stopSeeding(task: Aria2Task) {
    const { gid } = task
    try {
      await api.forcePauseTask({ gid })
      await api.removeTask({ gid })
      // Purge from aria2's stopped list so force-save=true won't persist it
      // in the session file. Without this, the stopped BT task reloads on
      // restart and enters seeding again (bt-seed-unverified=true).
      try {
        await api.removeTaskRecord({ gid })
      } catch (e) {
        logger.debug('TaskOps.stopSeeding', `removeTaskRecord gid=${gid} skipped: ${e}`)
      }
      // Also purge the parent metadata task from aria2's stopped list.
      // For magnet links, the metadata resolution task (GID-A) stays in
      // tellStopped with followedBy=[this GID] and the same infoHash.
      // If not cleaned up, its infoHash poisons mergeHistoryIntoTasks
      // dedup, causing the download task's history record to be discarded.
      if (task.following) {
        try {
          await api.removeTaskRecord({ gid: task.following })
        } catch (e) {
          logger.debug('TaskOps.stopSeeding', `removeTaskRecord following=${task.following} skipped: ${e}`)
        }
      }
      const record = buildBtCompletionRecord(task)
      const historyStore = useHistoryStore()
      // Clean up stale DB records from previous sessions (different GID, same infoHash)
      if (task.infoHash) {
        await historyStore.removeByInfoHash(task.infoHash, task.gid)
      }
      await historyStore.addRecord(record)
      // Clean up .aria2 control file left behind by force-save=true.
      // Best-effort: must never prevent fetchList/saveSession from running.
      try {
        await cleanupAria2ControlFile(task)
      } catch (e) {
        logger.debug('TaskOps.stopSeeding', `cleanupControlFile gid=${gid} skipped: ${e}`)
      }
      // Clean up hex40-named .torrent / .meta4 metadata left by bt-save-metadata
      // and rpc-save-upload-metadata. Covers session-restore case where onBtComplete
      // was suppressed by initialScanDone.
      if (task.dir && task.infoHash) {
        try {
          await cleanupAria2MetadataFiles(task.dir, task.infoHash)
        } catch (e) {
          logger.debug('TaskOps.stopSeeding', `cleanupMetadata gid=${gid} skipped: ${e}`)
        }
      }
      logger.info('TaskOps.stopSeeding', `gid=${gid} infoHash=${task.infoHash ?? 'n/a'}`)
    } finally {
      await fetchList()
      await api.saveSession()
    }
  }

  async function stopAllSeeding(): Promise<number> {
    const seeders = taskList.value.filter(checkTaskIsSeeder)
    if (seeders.length === 0) return 0
    await Promise.allSettled(seeders.map((t) => stopSeeding(t)))
    logger.info('TaskOps.stopAllSeeding', `stopped ${seeders.length} seeder(s)`)
    return seeders.length
  }

  async function removeTaskRecord(task: Aria2Task) {
    const { gid, status } = task
    if (gid === currentTaskGid.value) hideTaskDetail()
    const { ERROR, COMPLETE, REMOVED } = TASK_STATUS
    if ([ERROR, COMPLETE, REMOVED].indexOf(status) === -1) return
    const historyStore = useHistoryStore()
    await historyStore.removeRecord(gid)
    try {
      await api.removeTaskRecord({ gid })
    } catch (e) {
      logger.debug('TaskStore.removeTaskRecord.aria2', e)
    }
    await fetchList()
    await api.saveSession()
  }

  async function purgeTaskRecord() {
    const historyStore = useHistoryStore()
    await historyStore.clearRecords()
    try {
      await api.purgeTaskRecord()
    } catch (e) {
      logger.debug('TaskStore.purgeTaskRecord.aria2', e)
    }
    await fetchList()
    await api.saveSession()
  }

  async function batchRemoveTask(gids: string[]) {
    try {
      await api.batchRemoveTask({ gids })
      // Purge each gid from aria2's stopped-result list so force-save=true
      // (BT/magnet) won't persist entries in the session file on exit.
      for (const gid of gids) {
        try {
          await api.removeTaskRecord({ gid })
        } catch (e) {
          logger.debug('TaskOps.batchRemoveTask', `removeTaskRecord gid=${gid} skipped: ${e}`)
        }
      }
      logger.info('TaskOps.batchRemoveTask', `removed ${gids.length} task(s) gids=[${gids.join(',')}]`)
    } finally {
      await fetchList()
      await api.saveSession()
    }
  }

  async function hasActiveTasks(): Promise<boolean> {
    try {
      const tasks = await api.fetchTaskList({ type: TASK_STATUS.ACTIVE })
      return tasks.some(
        (t) => (t.status === TASK_STATUS.ACTIVE && !checkTaskIsSeeder(t)) || t.status === TASK_STATUS.WAITING,
      )
    } catch (e) {
      logger.debug('TaskOps.hasActiveTasks', `fetchTaskList failed: ${e}`)
      return false
    }
  }

  async function hasPausedTasks(): Promise<boolean> {
    try {
      const tasks = await api.fetchTaskList({ type: TASK_STATUS.ACTIVE })
      return tasks.some((t) => t.status === TASK_STATUS.PAUSED)
    } catch (e) {
      logger.debug('TaskOps.hasPausedTasks', `fetchTaskList failed: ${e}`)
      return false
    }
  }

  async function saveSession() {
    await api.saveSession()
  }

  return {
    removeTask,
    pauseTask,
    resumeTask,
    pauseAllTask,
    resumeAllTask,
    toggleTask,
    stopSeeding,
    stopAllSeeding,
    removeTaskRecord,
    purgeTaskRecord,
    batchRemoveTask,
    hasActiveTasks,
    hasPausedTasks,
    saveSession,
  }
}
